library(rjson)

queryRequest = '{
                  "query":"Electriciteit de France",
                  "type":"Category:Energy_Company",
                  "properties":[
                    {
                      "pid":"Country",
                      "v":"France"
                    }
                  ]
                }'


queryRequest = '{
                  "q0":{
                    "query":"RWE Power AG",
                    "type":"Category:Energy_Company",
                    "type_strict":"should"
                  },
                  "q1":{
                    "query":"Vattenfall Europe Generation AG",
                    "type":"Category:Energy_Company",
                    "type_strict":"should"
                  }
                }'

queryRequest = '{"q0":{"query":"Klingenberg","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"}]},"q1":{"query":"Niederwartha","type":"Category:Powerplant","type_strict":"should","properties":[]},"q2":{"query":"Wedel","type":"Category:Powerplant","type_strict":"should","properties":[]},"q3":{"query":"Thyrow","type":"Category:Powerplant","type_strict":"should","properties":[]},"q4":{"query":"Reuter West","type":"Category:Powerplant","type_strict":"should","properties":[]},"q5":{"query":"Windpark J\xc3\xa4nschwalde","type":"Category:Powerplant","type_strict":"should","properties":[]},"q6":{"query":"Brunsb\xc3\xbcttel","type":"Category:Powerplant","type_strict":"should","properties":[]},"q7":{"query":"Geesthacht","type":"Category:Powerplant","type_strict":"should","properties":[]},"q8":{"query":"Windpark alpha ventus","type":"Category:Powerplant","type_strict":"should","properties":[]},"q9":{"query":"Tiefstack","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"}]}}'

queryRequest = '{"query":"Klingenberg","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe W\xc3\xa4rme Aktiengesellschaft"}]}'

queryRequest = '{"q0":{"query":"Ahrensfelde","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe Generation AG"},{"pid":"point","v":"52.58195, 13.56734"}]},"q1":{"query":"Markersbach","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe Generation AG"},{"pid":"point","v":"50.52133, 12.87778"}]},"q2":{"query":"IKW R\xc3\xbcdersdorf","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe New Energy Ecopower GmbH"},{"pid":"point","v":"52.49099, 13.82981"}]},"q3":{"query":"Wilmersdorf","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe W\xc3\xa4rme AG"},{"pid":"point","v":"52.47966, 13.30782"}]},"q4":{"query":"EBS-HKW Rostock","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe New Energy Ecopower GmbH"},{"pid":"point","v":"54.14582, 12.13999"}]},"q5":{"query":"Thyrow","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe Generation AG"},{"pid":"point","v":"52.227691, 13.319105"}]},"q6":{"query":"Schwarze Pumpe","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe Generation AG"},{"pid":"point","v":"51.53552999999999, 14.36422"}]},"q7":{"query":"Boxberg","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe Generation AG"},{"pid":"point","v":"51.4076272, 14.5723372"}]},"q8":{"query":"Mitte","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe W\xc3\xa4rme AG"},{"pid":"point","v":"52.5100529, 13.420037"}]},"q9":{"query":"Charlottenburg","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe W\xc3\xa4rme AG"},{"pid":"point","v":"52.52135, 13.31023"}]}}'

queryRequest = '{"query":"Ahrensfelde","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"owner","v":"Vattenfall Europe Generation AG"},{"pid":"point","v":"52.58195, 13.56734"}]}'

queryRequest = '{"q0":{"query":"Rugeley ","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"International Power / Mitsui"}]},"q1":{"query":"Slieve Divena","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"Infinis"}]},"q2":{"query":"Castleford","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"E.On UK"}]},"q3":{"query":"Arnish","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"Scottish & Southern Energy plc"}]},"q4":{"query":"Lubreoch","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"Scottish & Southern Energy plc"}]},"q5":{"query":"Hare Hill","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"Scottish Power"}]},"q6":{"query":"Bowbeat","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"E.On UK"}]},"q7":{"query":"Walkaway","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"EDF Energy Renewables"}]}}'

queryRequest = '{"query":"Rugeley ","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"International Power / Mitsui"}]},"q1":{"query":"Slieve Divena","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"owner","v":"Infinis"}]}'

queryRequest = '{"q0":{"query":"Erdgasverdichterstation Eischleben","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"50.8900918"},{"pid":"longitude","v":"10.9868779"},{"pid":"owner","v":"WINGAS TRANSPORT GmbH"}]},"q1":{"query":"HKW Mitte","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"52.5098"},{"pid":"longitude","v":"13.421"},{"pid":"owner","v":"Vattenfall Europe W\xc3\xa4rme Aktiengesellschaft"}]},"q2":{"query":"14310-0753","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"51.42305"},{"pid":"longitude","v":"8.02866"},{"pid":"owner","v":"Perstorp Chemicals GmbH Perstorp Chemicals GmbH"}]},"q3":{"query":"GuD Hamm - TGH","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"51.67316"},{"pid":"longitude","v":"7.93035"},{"pid":"owner","v":"Trianel Gaskraftwerk Hamm GmbH & Co. KG"}]},"q4":{"query":"14310-1300","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"53.55412"},{"pid":"longitude","v":"9.90264"},{"pid":"owner","v":"E.ON Hanse W\xc3\xa4rme GmbH"}]},"q5":{"query":"14310-1210","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"50.78467"},{"pid":"longitude","v":"6.51565"},{"pid":"owner","v":"Globalis Service GmbH & Co. KG"}]},"q6":{"query":"Heizkraftwerk Neubrandenburg","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"53.56276"},{"pid":"longitude","v":"13.2958"},{"pid":"owner","v":"Neubrandenburger Stadtwerke GmbH Neubrandenburger Stadtwerke GmbH"}]},"q7":{"query":"14310-0043","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"48.78187"},{"pid":"longitude","v":"10.09965"},{"pid":"owner","v":"Carl Zeiss AG"}]},"q8":{"query":"14310-0303","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"50.73771"},{"pid":"longitude","v":"12.38814"},{"pid":"owner","v":"Stadtwerke Werdau GmbH Stadtwerke Werdau GmbH"}]},"q9":{"query":"Anlage H111 Biberach","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"48.11091"},{"pid":"longitude","v":"9.79834"},{"pid":"owner","v":"Boehringer Ingelheim Pharma GmbH & Co KG"}]}}'

queryRequest = '{"query":"Erdgasverdichterstation Eischleben","type":"Category:Powerplant","type_strict":"should","properties":[{"pid":"country","v":"Germany"},{"pid":"latitude","v":"50.8900918"},{"pid":"longitude","v":"10.9868779"},{"pid":"owner","v":"WINGAS TRANSPORT GmbH"}]}'

queryRequest = fromJSON(queryRequest)